### ISSUE TITLE
How to run stacey?

### ISSUE THREAD

**Issue by nafisahmad** [ParthVaidya962/VirtualAssistantStacey#2]
hi, great project!
can you please give a brief about requirements and how to run it on windows?

**Comment by ParthVaidya962** [comment]
Thank you for your feedback, I really appreciate it.
Regarding your issue, The project is under development at present and hence does not contain documentation and other information regarding setup and execution of the program at present.
The project is expected to be complete in around a week or so from the date of this comment. So you can expect proper details and an updated "readme.md" file soon enough.

In case of any further issues, feel free to post here.
and please make sure that you credit my work if you are using it either personally or commercially as this is my final year project and if someone uses it without credit, they may get under legal troubles.
Thank you,
Parth Vaidya.
